export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS';
export const SEARCH_CHARACTERS_FAIL = 'SEARCH_CHARACTERS_FAIL';
export const SEARCH_CHARACTERS_SUCCESS = 'SEARCH_CHARACTERS_SUCCESS';

export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const ADD_TO_LIST = 'ADD_TO_LIST';

export const SAVE_TO_LOCAL_STORAGE = 'SAVE_TO_LOCAL_STORAGE';
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';

export const LOADING_CHARACTERS = 'LOADING_CHARACTERS';
